[ServerConfig]
host = "127.0.0.1"
port = "8081"

[Redis]
host = "127.0.0.1"
port = "6379"

[DB]
host = "127.0.0.1"
port = "3306"
username = "root"
password = "Mysql20191105."
dbname = "lottery"
charset = "utf8mb4"